version: "3.1"
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aagat
      POSTGRES_PASSWORD: aagat
      POSTGRES_DB: ecommerce
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
